name: Build Windows EXE

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pillow pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --noconsole --onefile --name ImageConverter Pillow.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ImageConverter-EXE
          path: dist/ImageConverter.exe
